import torch
from einops import rearrange, reduce, repeat

x = torch.randn(2, 3, 4, 5)   # (batch, channel, height, width)
print("Original shape:", x.shape)
view_shape = x.view(2, -1)
print("View shape:", view_shape.shape)
reshape_shape = x.reshape(2, -1)
print("Reshape shape:", reshape_shape.shape)
permute_shape = x.permute(0, 2, 3, 1)
print("Permute shape:", permute_shape.shape)
transpose_shape = x.transpose(1, 2)
print("Transpose shape:", transpose_shape.shape)
unsqueeze_shape = x.unsqueeze(1)
print("Unsqueeze shape:", unsqueeze_shape.shape)
squeeze_shape = x.squeeze()
print("Squeeze shape:", squeeze_shape.shape)
expand_shape = x.expand(-1, -1, -1, -1)
print("Expand shape:", expand_shape.shape)
rearrange_shape = rearrange(x, "b c h w -> b (h w) c") 
print("Rearrange shape:", rearrange_shape.shape)
rearrange_shape = rearrange(x, "b (g c) h w -> b g c h w", g=3)
print("Rearrange shape:", rearrange_shape.shape)
reduce_shape = reduce(x, "b c h w -> b c", "mean")
print("Reduce shape:", reduce_shape.shape)
repeat_shape = repeat(x, "b c h w -> b c (h 2) w")
print("Repeat shape:", repeat_shape.shape)

print("View shape:", view_shape.shape)
print("Reshape shape:", reshape_shape.shape)
print("Permute shape:", permute_shape.shape)
print("Transpose shape:", transpose_shape.shape)
print("Unsqueeze shape:", unsqueeze_shape.shape)
print("Squeeze shape:", squeeze_shape.shape)
print("Expand shape:", expand_shape.shape)
print("Rearrange shape:", rearrange_shape.shape)
print("Reduce shape:", reduce_shape.shape)
print("Repeat shape:", repeat_shape.shape)
